### ISSUE TITLE
如何得到密集的深度图？

### ISSUE THREAD

**Issue by rockywind** [YinminZhang/MonoGeo#1]
你好，请教个问题，MonoGeo输出的是密集深度图，但是，公式6是基于每个实例的2D框高度得到的，对于没有2D框的区域，MonoGeo如何输出深度[好奇]
![image](https://user-images.githubusercontent.com/14838781/128837675-e3aed1fb-0f22-4bb4-b707-ddf86cb322d4.png)

**Comment by YinminZhang** [comment]
1. The 2D/3D predictions are dense maps, therefore the depth map is also a dense map. 
2. The supervision is selected through the mask, so the supervision signal is sparse.

**Comment by rockywind** [comment]
As I knew, the 2D/3D predictions are decoded from output branches, which are consist of Heatmap, 2D offset, 3D offset, 2D size, 3D dimension, and Orientation. How to generate the dense depth map?

**Comment by YinminZhang** [comment]
The 2D/3D predictions from the convolution network are dense maps. And then, we directly decode these prediction maps to generate the depth map through Eq. 6.

**Comment by YinminZhang** [comment]
I think this issue could be closed. Please feel free to reopen with any follow ups.
